# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: mypool


steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'installing Modules in /client'
  inputs:
    command: 'install'
    workingDir: 'client'
- task: Npm@1
  displayName: 'installing Modules in /doc-appoinment-system'
  inputs:
    command: 'install'
    workingDir: 'doc-appoinment-system'
- task: Npm@1
  displayName: 'Building Modules in /client'
  inputs:
    command: 'custom'
    workingDir: 'client'
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    Contents: |
      .github/**
      client/build/**
      client/public/**
      client/src/**
      client/.gitigore**
      client/package-lock.json**
      client/package.json**
      client/README.md**
      config/**
      controllers/**
      middlewares/**
      models/**
      routes/**
      .env**
      package-lock.json**
      package.json**
      server.js**
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'